layout_spectrum: 1
name: Viagens Maneiras
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7748735
  lightness: 0.2706577
  saturation: 0.4021922
  rhythmicContrast: 0.7664418
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#434343'
    - '#D7D7D7'
    - '#B5B5B5'
typography_spectrum: 0.09865092
