layout_spectrum: 0.8962901
typography_spectrum: 0.4399945
color:
  lightness: 0.1528248
  brandStrength: 0.8134266
  saturation: 0.5623115
  rhythmicContrast: 0.8978443
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#424242'
    - '#C6C6C6'
    - '#888888'
name: Viagens Maneiras
