layout_spectrum: 0.8962901
name: Viagens Maneiras
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7748735
  lightness: 0.6214165
  saturation: 0.7023609
  rhythmicContrast: 0.6922429
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#424242'
    - '#C6C6C6'
    - '#888888'
typography_spectrum: 0
