layout_spectrum: 0.8962901
name: Viagens Maneiras
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.118887
color:
  brandStrength: 0.8134266
  lightness: 0.3937605
  saturation: 0.5623115
  rhythmicContrast: 0.8978443
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#424242'
    - '#C6C6C6'
    - '#888888'
